<?xml version="1.0"?>
<robot>
  <property name="M_PI" value="3.14159"/>
  <property name="M_SCALE" value="0.01"/>
  <property name="HOKUYO_RADIUS" value="0.02"/>
  <property name="HOKUYO_LENGTH" value="0.07"/>
  <property name="KINECT_LENGTH" value="0.064"/>
  <property name="KINECT_WIDTH" value="0.121"/>
  <property name="KINECT_HEIGHT" value="0.0381"/>
  
  <!-- WHEEL -->
  <macro name="wheel" params="parent name *origin *axis">
    <joint name="${name}_joint" type="continuous">
      <insert_block name="origin" />
      <insert_block name="axis" />
      <parent link="${parent}"/>
      <child link="${name}_link" />
    </joint>
    
    <link name="${name}_link">
      <inertial>
        <mass value="0.00001" />
        <origin xyz="0 0 0" />
        <inertia ixx="1.0" ixy="0.0" ixz="0.0"
          iyy="1.0" iyz="0.0"
          izz="1.0" />
      </inertial>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://robotino_description/meshes/RobotinoWheel.dae" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
        </geometry>
      </visual>
    </link>
  </macro>
  
  <!-- COMMAND BRIDGE -->
  <macro name="command_bridge" params="parent name *origin">
    <joint name="${name}_joint" type="fixed">
      <insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${name}_link" />
    </joint>
    
    <link name="${name}_link">
      <inertial>
        <mass value="0.00001" />
        <origin xyz="0 0 0" />
        <inertia ixx="1.0" ixy="0.0" ixz="0.0"
          iyy="1.0" iyz="0.0"
          izz="1.0" />
      </inertial>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.25 0.11 0.16"/>
        </geometry>
      </collision>
    </link>
  </macro>
  
  <!-- LASER SCANNER -->
  <macro name="laser" params="parent name *origin">
    <joint name="${name}_joint" type="fixed">
      <insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${name}_link" />
    </joint>
    
    <link name="${name}_link">
      <inertial>
        <mass value="0.00001" />
        <origin xyz="0 0 0" />
        <inertia ixx="1.0" ixy="0.0" ixz="0.0"
          iyy="1.0" iyz="0.0"
          izz="1.0" />
      </inertial>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 ${M_PI/2}" />
        <geometry>
          <mesh filename="package://robotino_description/meshes/RobotinoLaserScanner.dae" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
        </geometry>
      </visual>

      <collision>
        <origin xyz="0 0 ${HOKUYO_LENGTH/2}" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${HOKUYO_RADIUS}" length="${HOKUYO_LENGTH}" />
        </geometry>
      </collision>
    </link>
  </macro>
  
  <!-- Camera -->
  <macro name="camera" params="parent name *origin">
    <joint name="${name}_joint" type="fixed">
      <insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${name}_link" />
    </joint>
    
    <link name="${name}_link">
      <inertial>
        <mass value="0.00001" />
        <origin xyz="0 0 0" />
        <inertia ixx="1.0" ixy="0.0" ixz="0.0"
          iyy="1.0" iyz="0.0"
          izz="1.0" />
      </inertial>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://robotino_description/meshes/RobotinoCamera.dae" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
        </geometry>
      </visual>
    </link>
  </macro>
  
  <!-- AngleBracket With USB Hub -->
  <macro name="anglebracketusb" params="parent name *origin">
    <joint name="${name}_joint" type="fixed">
      <insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${name}_link" />
    </joint>
    
    <link name="${name}_link">
      <inertial>
        <mass value="0.00001" />
        <origin xyz="0 0 0" />
        <inertia ixx="1.0" ixy="0.0" ixz="0.0"
          iyy="1.0" iyz="0.0"
          izz="1.0" />
      </inertial>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://robotino_description/meshes/AngleBracketUSBHub.dae" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
        </geometry>
      </visual>
    </link>
  </macro>
  
  <!-- KINECT -->
  <macro name="kinect" params="parent name color llimit ulimit vlimit *origin">
    <joint name="${name}_joint" type="revolute">
      <insert_block name="origin" />
      <axis xyz="0 1 0"/>
      <limit effort="30" velocity="${vlimit}" lower="${llimit}" upper="${ulimit}" />
      <parent link="${parent}"/>
      <child link="${name}_link" />
    </joint>
    
    <link name="${name}_link">
      <inertial>
        <mass value="0.00001" />
        <origin xyz="0 0 0" />
        <inertia ixx="1.0" ixy="0.0" ixz="0.0"
          iyy="1.0" iyz="0.0"
          izz="1.0" />
      </inertial>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${KINECT_LENGTH} ${KINECT_WIDTH} ${KINECT_HEIGHT}"/>
        </geometry>
        <material name="${color}"/>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${KINECT_LENGTH} ${KINECT_WIDTH} ${KINECT_HEIGHT}"/>
        </geometry>
      </collision>
    </link>
  </macro>
</robot>